### ISSUE TITLE
Is this still getting updated?

### ISSUE THREAD

**Issue by fujnw** [hiring-lab/job_postings_tracker#100]
It's been a month since the last update. Will this data still get weekly updates?

**Comment by Odoherr** [comment]
Similarly I have noticed that this data set is no longer being up dated. No comment in regards to it discontinuation was published either here nor on the Hiring Lab site. We queries this directly with them (hiringlabinfo@indeed.com) but no response has been made to our email queries. 

Hiring Lab, can you please advise if this is still getting updated going forward?

**Comment by MattCowgill** [comment]
@nbunker

**Comment by nbunker** [comment]
Apologies for the delay. The data have been updated and will be regularly updated moving forward.

**Comment by MattCowgill** [comment]
👍
