### ISSUE TITLE
growth in supervisory positions?

### ISSUE THREAD

**Issue by michelezanini** [hiring-lab/job_postings_tracker#97]
Dear Hiring Lab team, thanks for making this data available--it's incredibly valuable.  I'm an organizational researcher interested in the growth of managerial occupations in the US and other countries, and I've been national statistics (BLS data in case of the US) to track this trend over time.  I'd be very curious to understand what your job posting data shows... my hypothesis is that supervisory/managerial have grown rapidly since Feb of 2020.  Is this something you'd be willing to share, either publicly or privately?  I can be reached at michele@managementlab.org.  Thanks again for your generosity...

-Michele

**Comment by nbunker** [comment]
Hi, Michele. Thanks for your interest. We are not able to share data that tracks trends specifically for managerial or non-managerial roles. Best of luck with your research!

**Comment by michelezanini** [comment]
thanks for letting me know, Nick.  We're going to be revising our 2020 WSJ Bestselling Book, Humanocracy, later this year, and looking for updated data on occupational dynamics.  So if it becomes at all possible to share with us, confidentially and with attribution, the job posting data that differentiates supervisory positions from non-supervisory ones, please let me know...  Keep up the great work!

**Comment by michelezanini** [comment]
Thanks for letting me know, Nick.  We're going to be revising our 2020 WSJ Bestselling Book, Humanocracy, later this year, and looking for updated data on occupational dynamics.  So if it becomes at all possible to share with us, confidentially and with attribution, the job posting data that differentiates supervisory positions from non-supervisory ones, please let me know...  Keep up the great work!
